"""empty message

Revision ID: 314c93eb1ab4
Revises: 
Create Date: 2018-03-22 19:23:49.928559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314c93eb1ab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('created_on', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserProfile')
    # ### end Alembic commands ###
